import type { Metadata } from "next";
import Navigation from "@/components/Navigation";
import "./globals.css";
// import { Geist, Geist_Mono } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
	title: "Andrew's Portfolio Website",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`antialiased w-screen h-screen`}>
				<div className="flex flex-col w-full space-y-3 md:flex-row md:space-x-5 md:ml-32 md:mt-32">
					<Navigation />
					{children}
				</div>
			</body>
		</html>
	);
}
